#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : templated-dictionary
Version  : 1.1
Release  : 2
URL      : file:///aot/build/clearlinux/packages/templated-dictionary/templated-dictionary-v1.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/templated-dictionary/templated-dictionary-v1.1.tar.gz
Summary  : Dictionary with Jinja2 expansion
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: templated-dictionary-python = %{version}-%{release}
Requires: templated-dictionary-python3 = %{version}-%{release}
Requires: Jinja2
BuildRequires : Jinja2
BuildRequires : buildreq-distutils3
BuildRequires : distro
BuildRequires : findutils
BuildRequires : pep517
BuildRequires : pyroute2
BuildRequires : python-build
BuildRequires : python3
BuildRequires : setuptools-python
BuildRequires : six

%description
# templated-dictionary
This module provides dictionary where every item is evaluated as a Jinja2 expression.

%package python
Summary: python components for the templated-dictionary package.
Group: Default
Requires: templated-dictionary-python3 = %{version}-%{release}

%description python
python components for the templated-dictionary package.


%package python3
Summary: python3 components for the templated-dictionary package.
Group: Default
Requires: python3-core
Provides: pypi(templated_dictionary)
Requires: pypi(jinja2)

%description python3
python3 components for the templated-dictionary package.


%prep
%setup -q -n templated-dictionary
cd %{_builddir}/templated-dictionary

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1628431549
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
if [ ! -f setup.py ]; then
printf "#!/usr/bin/env python\nfrom setuptools import setup\nsetup()" > setup.py
chmod +x setup.py
python3 setup.py build
else
python3 setup.py build
fi

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
